openapi: 3.0.2

info:
  title: REST API for the lifap5-backend-2019-2020
  description: The yaml description of the API, lively available at http://lifap5.univ-lyon1.fr/
  version: '0.4.1'
  contact:
    email: romuald.thion@univ-lyon1.fr
    name: Romuald THION
  license:
    name: CC BY-NC-SA 3.0 FR
    url: 'https://creativecommons.org/licenses/by-nc-sa/3.0/fr/'

servers:
  - url: 'https://lifap5.univ-lyon1.fr/'
    description: The public production server
  - url: 'http://localhost:3000/'
    description: A local development server

tags:
  - name: users
    description: Users related features, including whoami and your answers
  - name: quizzes
    description: Quizzes CRUD features,
  - name: questions
    description: Questions and theirs related propositions CRUD features (w.r.t. a quiz)
  - name: answers
    description: Retrieve, post and delete answers to quizzes
  - name: search
    description: minimalistic search engine
  - name: public
    description: Everyone one, without authentication
  - name: authenticated
    description: Authentified user (by x-api-key)

paths:
  /:
    get:
      summary: The index page
      description: The index page
      operationId: sendIndex
      tags:
        - public
      responses:
        200:
          description: The index page
          content:
            application/json:
              schema:
                type: object
                properties:
                  appname:
                    type: string
                  version:
                    type: string
                  description:
                    type: string
                required:
                  - appname
                  - version
                  - description
            text/html:
              schema:
                type: string
              example: <html>The index page</html>

  /echo/:
    post:
      description: Echo service that returns the json body, like ping with json
      operationId: echoHandler
      tags:
        - public
      requestBody:
        content:
          application/json:
            schema:
              description: The content to echo
              type: object
            example:
              msg: 'test'
              val: 42
      responses:
        200:
          description: Echoed input
          content:
            application/json:
              schema:
                description: The echoed content
                type: object
              example:
                msg: 'test'
                val: 42
        # default:
        #   $ref: "#/components/responses/error"

  /stream/:
    get:
      description: Websocket that stream updates on serveur to the client. WARNING this features cannot be tested HERE 
      operationId: broadcastNotifications
      tags:
        - public
      responses:
        200:
          description: An update message that tells which quiz is updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    enum: [quiz, question, operation, answer]
                  operation:
                    type: string
                    enum: [INSERT, UPDATE, DELETE]
                  quiz_id:
                    type: integer
                  time:
                    type: string
              example:
                type: 'quiz'
                operation: 'INSERT'
                quiz_id: 3
                time: "2020-03-29T19:01:25.847158+02:00"
              
        # default:
        #   $ref: "#/components/responses/error"

  /not-implemented/:
    get:
      summary: Always returns a NotImplemented error
      description: An error page for test purposes
      operationId: notImplemented
      tags:
        - public
      responses:
        501:
          $ref: '#/components/responses/NotImplemented'

  /healthcheck/:
    get:
      summary: Checks if server is OK
      description: Tests if the PostgreSQL backend is up
      operationId: onHealthCheck
      tags:
        - public
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectHealthCheck'

  /search/:
    get:
      description: Full-text search service
      operationId: searchHandler
      tags:
        - public
        - search
      parameters:
        - in: query
          name: q
          schema:
            type: string
            default: 'alan OR alonzo'
          description: The query to search for, in search engine style. Searches in all text fields and user's id
      responses:
        200:
          description: The results, ordered by rank from highest to lowest
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    quiz_id:
                      type: integer
                    question_id:
                      type: integer
                    proposition_id:
                      type: integer
                    text:
                      type: string
                    rank:
                      type: number

  /users/:
    get:
      summary: All users
      description: The list of all users with pagination, at most pageLimit items (default 50)
      operationId: getAllUsersHandler
      tags:
        - public
        - users
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: The number of pages to skip, so (page-1)*pageLimit items are skipped
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectPaginatedUsers'

  /users/whoami:
    get:
      summary: Given your own infos
      description: Basic route to check authentication with x-api-key
      operationId: whoamiHandler
      tags:
        - authenticated
        - users
      security:
        - XApiKeyAuth: []
      responses:
        200:
          description: When OK, answers with ID, first name and last name
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectUser'
            text/html:
              schema:
                type: string
              example: <html>A welcome page</html>
        401:
          $ref: '#/components/responses/Unauthorized'

  /users/answers:
    get:
      summary: Give your answers to quizzes
      description: Details include the answered questions
      operationId: getUserAnswers
      tags:
        - authenticated
        - users
        - answers
      security:
        - XApiKeyAuth: []
      responses:
        200:
          description: The list of answers, grouped by quizzes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectUserDetail'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'

  /users/quizzes:
    get:
      summary: Give the quizzes you ve created
      description: Similar to the /quizzes routes but only for your quizzes
      operationId: getUserQuizzes
      tags:
        - authenticated
        - users
        - quizzes
      security:
        - XApiKeyAuth: []
      responses:
        200:
          description: The list of quizzes
          content:
            application/json:
              schema:
                type: array
                items:
                  schema:
                  $ref: '#/components/schemas/ObjectQuiz'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'

  /quizzes/:
    get:
      summary: All quizzes
      description: The list of all quizzes  with pagination, at most pageLimit items (default 50)
      operationId: getAllQuizzesHandler
      tags:
        - public
        - quizzes
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: The number of pages to skip, so (page-1)*limit items are skipped
        - in: query
          name: limit
          schema:
            type: integer
            default: 50
          description: The number of results by page
        - in: query
          name: order
          schema:
            type: string
            enum: ['quiz_id', 'created_at', 'title', 'owner_id']
            default: quiz_id
          description: The order to sort results on
        - in: query
          name: dir
          schema:
            type: string
            enum: ['asc', 'desc']
            default: asc
          description: The order to sort results on
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectPaginatedQuizzes'

    post:
      summary: Creates a new quiz
      description: Creates a quiz, in the database. quiz_id is auto generated, owner_id is set to current user, title and description are mandatory
      operationId: postQuizHandler
      tags:
        - authenticated
        - quizzes
      security:
        - XApiKeyAuth: []
      requestBody:
        description: The quizz to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectQuiz'
            example:
              title: 'QCM de test'
              description: 'Un QCM supplémentaire'
      responses:
        201:
          description: Content created, returns the quiz's id
          content:
            application/json:
              schema:
                type: object
                properties:
                  quiz_id:
                    type: integer
                    example: 42
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        409:
          $ref: '#/components/responses/Conflict'

  /quizzes/{quiz_id}/:
    parameters:
      - $ref: '#/components/parameters/quizIdParam'
    get:
      summary: Get one quiz
      description: Retrieve the given quizz if it exists
      operationId: getOneQuizHandler
      tags:
        - public
        - quizzes
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ObjectQuiz'
        404:
          $ref: '#/components/responses/NotFound'
    put:
      summary: Update an existing quiz
      description: attributes created_at, quiz_id and owner_id cannot be modified, owner_id must be current user
      operationId: putQuizHandler
      tags:
        - authenticated
        - quizzes
      security:
        - XApiKeyAuth: []
      requestBody:
        description: The the fields to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectQuiz'
            example:
              title: 'QCM de test - màj'
              description: 'Un QCM supplémentaire - màj'
              open: true
      responses:
        200:
          description: Content updated, returns the whole quizz
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectQuiz'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
    delete:
      summary: Delete an existing quiz
      description: owner_id must be current user
      operationId: delQuizHandler
      tags:
        - authenticated
        - quizzes
      security:
        - XApiKeyAuth: []
      responses:
        200:
          description: Content deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  quiz_id:
                    type: integer
                    example: 42
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'

  /quizzes/{quiz_id}/questions/:
    parameters:
      - $ref: '#/components/parameters/quizIdParam'
    get:
      summary: All questions of a quizz
      description: All questions of a given quizz (if it exists) with extra information
      operationId: getAllQuestionsHandler
      tags:
        - public
        - questions
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ObjectQuestionDetail'
        404:
          $ref: '#/components/responses/NotFound'
    post:
      summary: Add a question to a quizz
      operationId: postQuestionHandler
      tags:
        - authenticated
        - questions
      security:
        - XApiKeyAuth: []
      requestBody:
        description: The question to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectQuestionDetail'
            example:
              question_id: 0
              sentence: 'Qui a inventé le lambda calcul ?'
              propositions:
                - content: 'Alan Turing'
                  proposition_id: 0
                  correct: false
                - content: 'Alonzo Church'
                  proposition_id: 1
                  correct: true
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - quiz_id
                  - question_id
                properties:
                  quiz_id:
                    type: integer
                  question_id:
                    type: integer
              example:
                quiz_id: 1
                question_id: 0
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'

  /quizzes/{quiz_id}/questions/{question_id}/:
    parameters:
      - $ref: '#/components/parameters/quizIdParam'
      - $ref: '#/components/parameters/questionIdParam'
    get:
      summary: A specific question of a quizz
      description: A question of a given quizz with detailled information (its propositions) but without answers
      operationId: getOneQuestionHandler
      tags:
        - public
        - questions
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ObjectQuestionDetail'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
    put:
      summary: Update a question of a quizz and its propositions
      operationId: putQuestionHandler
      tags:
        - authenticated
        - questions
      security:
        - XApiKeyAuth: []
      requestBody:
        description: The question to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectQuestionDetail'
            example:
              sentence: 'Qui a encore pas inventé le lambda calcul ?'
              propositions:
                - content: 'encore Alan Turing'
                  proposition_id: 0
                  correct: true
                - content: 'encore Alonzo Church'
                  proposition_id: 1
                  correct: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  quiz_id:
                    type: integer
                    example: 0
                  question_id:
                    type: integer
                    example: 0
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete a question of a quizz and its propositions
      description: owner_id must be current user
      operationId: deleteQuestionHandler
      tags:
        - authenticated
        - questions  
      security:
        - XApiKeyAuth: []
      responses:
        200:
          description: Content deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  quiz_id:
                    type: integer
                    example: 0
                  question_id:
                    type: integer
                    example: 0
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'  

  /quizzes/{quiz_id}/questions/{question_id}/answers/:
    parameters:
      - $ref: '#/components/parameters/quizIdParam'
      - $ref: '#/components/parameters/questionIdParam'
    get:
      summary: All answers to a question of a quiz you own
      description: List all answers (grouped by propositions) of a quiz you own
      operationId: getOneQuestionAnswersHandler
      security:
        - XApiKeyAuth: []
      tags:
        - authenticated
        - answers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ObjectQuestionWithAnswers'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete your answer to a question
      description: It suppresses the chosen proposition for this question
      operationId: deleteAnswerHandler
      tags:
        - authenticated
        - answers
      security:
        - XApiKeyAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectAnswer'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'

  /quizzes/{quiz_id}/questions/{question_id}/answers/{proposition_id}:
    parameters:
      - $ref: '#/components/parameters/quizIdParam'
      - $ref: '#/components/parameters/questionIdParam'
      - $ref: '#/components/parameters/propositionIdParam'
    post:
      summary: Answer to a question with a proposition. If an answer to this question already exists, it updates it
      operationId: postAnswerHandler
      tags:
        - authenticated
        - answers
      security:
        - XApiKeyAuth: []
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectAnswer'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    userIdParam:
      name: user_id
      in: path
      description: ID of a user
      required: true
      schema:
        type: string
        example: 'test.user'
      style: simple

    quizIdParam:
      name: quiz_id
      in: path
      description: ID of a quiz
      required: true
      schema:
        type: integer
        example: 0
      style: simple

    questionIdParam:
      name: question_id
      in: path
      description: ID of a question (local to a quiz)
      required: true
      schema:
        type: integer
        example: 0
      style: simple

    propositionIdParam:
      name: proposition_id
      in: path
      description: ID of a proposition (local to a question)
      required: true
      schema:
        type: integer
        example: 1
      style: simple

  # https://swagger.io/docs/specification/authentication/api-keys/
  securitySchemes:
    XApiKeyAuth: # arbitrary name for the security scheme
      type: apiKey
      in: header # can be "header", "query" or "cookie"
      name: X-API-KEY # name of the header, query parameter or cookie

  responses:
    BadRequest:
      description: A 400 error, usually on invalid input (wrong type)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            name: BadRequest
            message: "Invalid content: 'xxx' is not an integer"
        text/html:
          schema:
            type: string
          example: <html>An error page with status, name and message</html>
    Unauthorized:
      description: A 401 error, for example when no or invalid UUID is provided in X-API-KEY header or when the UUID does not exist in the database
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            name: Unauthorized
            message: x-api-key is not provided or invalid
        text/html:
          schema:
            type: string
          example: <html>An error page with status, name and message</html>
    Forbidden:
      description: A 403 error, when the user is not the owner of the resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            name: Forbidden
            message: "Quiz #0 is not owned by test (owner is 'this guy')"
        text/html:
          schema:
            type: string
          example: <html>An error page with status, name and message</html>
    NotFound:
      description: A 404 error, for resource not found (quiz, user, question)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            name: NotFound
            message: Quiz 999 does not exist
        text/html:
          schema:
            type: string
          example: <html>An error page with status, name and message</html>
    Conflict:
      description: A 409 error, usually due to primary constraint violation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            name: Conflict
            message: Title "a title" already exists (no INSERT)
        text/html:
          schema:
            type: string
          example: <html>An error page with status, name and message</html>
    InternalServer:
      description: A 500 error, internal error that is generated by the final default handler if no status is specified
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            name: InternalServer
            message: database complains
        text/html:
          schema:
            type: string
          example: <html>An error page with status, name and message</html>
    NotImplemented:
      description: A 501 error, for features to appear
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            name: NotImplemented
            message: this route does no exist
        text/html:
          schema:
            type: string
          example: <html>An error page with status, name and message</html>

  schemas:
    Error:
      type: object
      properties:
        name:
          type: string
          enum: [BadRequest, Unauthorized, Forbidden, NotFound, InternalServer, NotImplemented]
        message:
          type: string
      required:
        - name
        - message

    ObjectHealthCheck:
      description: The object returned on healthcheck
      type: object
      required:
        - status
        - info
        - details
      properties:
        status:
          type: string
          enum:
            - ok
            - error
        info:
          type: array
          items:
            type: integer
            example: 1
        details:
          items:
            type: integer
            example: 1

    ObjectPaginatedList:
      type: object
      required:
        - currentPage
        - pageSize
        - nbResults
        - nbPages
      properties:
        currentPage:
          type: integer
          example: 6
        pageSize:
          type: integer
          example: 50
        nbResults:
          type: integer
          example: 252
        nbPages:
          type: integer
          example: 6

    ObjectPaginatedUsers:
      allOf:
        - $ref: '#/components/schemas/ObjectPaginatedList'
      required:
        - results
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              user_id:
                type: string
          example:
            - user_id: test.user
            - user_id: other.user

    ObjectPaginatedQuizzes:
      allOf:
        - $ref: '#/components/schemas/ObjectPaginatedList'
      required:
        - results
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/ObjectQuiz'

    ObjectUser:
      type: object
      required:
        - user_id
        - firstname
        - lastname
      properties:
        user_id:
          type: string
          example: test.user
        firstname:
          type: string
          example: test
        lastname:
          type: string
          example: user

    ObjectUserDetail:
      type: array
      items:
        type: object
        properties:
          quiz_id:
            description: value is auto generated by the database
            type: integer
            example: 1
          created_at:
            type: string
            format: date-time
            example: '2020-03-11T09:56:12.372Z'
          title:
            type: string
            example: 'QCM LIFAP5 #1'
          description:
            type: string
            example: Des questions de JS et lambda calcul
          owner_id:
            type: string
            example: test.user
          answers:
            type: array
            items:
              type: object
              properties:
                question_id:
                  type: integer
                proposition_id:
                  type: integer
                answered_at:
                  type: string
                  format: date-time

    ObjectQuiz:
      type: object
      required:
        - quiz_id
        - title
        - description
        - owner_id
      properties:
        quiz_id:
          description: value is auto generated by the database
          type: integer
          example: 1
        created_at:
          type: string
          format: date-time
          example: '2020-03-11T09:56:12.372Z'
        title:
          type: string
          example: 'QCM LIFAP5 #1'
        description:
          type: string
          example: Des questions de JS et lambda calcul
        owner_id:
          type: string
          example: test.user
        questions_number:
          type: integer
          example: 2
        questions_ids:
          type: array
          items:
            type: integer
          example: [0, 1]
        open:
          type: boolean
          example: false

    ObjectQuestion:
      type: object
      required:
        - quiz_id
        - question_id
        - sentence
      properties:
        quiz_id:
          description: value is auto generated by the database
          type: integer
          example: 0
        question_id:
          description: the question'is, the value is under user's control
          type: integer
          example: 0
        sentence:
          type: string
          description: the text of the question
          example: 'Qui a inventé le lambda calcul ?'
        propositions_number:
          type: integer
          description: the number of propositions
          example: 1
        correct_propositions_number:
          type: integer
          description: the number of correct propositions
          example: 1

    ObjectQuestionDetail:
      allOf:
        - $ref: '#/components/schemas/ObjectQuestion'
      required:
        - proposition
      properties:
        propositions:
          type: array
          items:
            $ref: '#/components/schemas/ObjectProposition'


    ObjectQuestionWithAnswers:
      allOf:
        - $ref: '#/components/schemas/ObjectQuestion'
      required:
        - proposition
      properties:
        propositions:
          type: array
          items:
            $ref: '#/components/schemas/ObjectPropositionWithAnswers'
        

    ObjectProposition:
      type: object
      required:
        - content
        - correct
        - proposition_id
      properties:
        content:
          type: integer
          example: 'Alan Turing'
        proposition_id:
          type: integer
          example: 0


    ObjectPropositionWithAnswers:
      allOf:
        - $ref: '#/components/schemas/ObjectProposition'
      required:
        - answers
      properties:
        answers:
          type: array
          items:
            type: object
            properties:
              user_id:
                type: string
                example: 'test.user'
              answered_at:
                type: string
                example: '2020-03-20T13:26:24.139Z'
            required:
              - answered_at
              - user_id


    ObjectAnswer:
      type: object
      properties:
        user_id:
          type: string
          example: 'test.user'
        quiz_id:
          type: integer
          example: 0
        question_id:
          type: integer
          example: 0
        proposition_id:
          type: integer
          example: 1
        answered_at:
          type: string
          example: '2020-03-20T13:26:24.139Z'
      required:
        - quiz_id
        - question_id
        - proposition_id
        - user_id
